### PR TITLE
add icons for various browsers

### LINKED ISSUE #88: Missing apple-touch icons
View details in Rollbar: [https://rollbar.com/habitat-nola-signin/habitat-nola-signin/items/6/](https://rollbar.com/habitat-nola-signin/habitat-nola-signin/items/6/)

```

ActionController::RoutingError: No route matches [GET] "/apple-touch-icon-120x120-precomposed.png"
  File "/app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/debug_exceptions.rb", line 21, in call
  File "/app/vendor/bundle/ruby/2.3.0/gems/rollbar-2.12.0/lib/rollbar/middleware/rails/show_exceptions.rb", line 22, in call_with_rollbar
  File "/app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/show_exceptions.rb", line 30, in call
  File "/app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/rack/logger.rb", line 38, in call_app
  File "/app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/rack/logger.rb", line 20, in block in call
  File "/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb", line 68, in block in tagged
  File "/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb", line 26, in tagged
  File "/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb", line 68, in tagged
  File "/app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/rack/logger.rb", line 20, in call
  File "/app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/request_id.rb", line 21, in call
  File "/app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/methodoverride.rb", line 22, in call
  File "/app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/runtime.rb", line 18, in call
  File "/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/cache/strategy/local_cache_middleware.rb", line 28, in call
  File "/app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/static.rb", line 120, in call
  File "/app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/sendfile.rb", line 113, in call
  File "/app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb", line 518, in call
  File "/app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/application.rb", line 165, in call
  File "/app/vendor/bundle/ruby/2.3.0/gems/puma-3.4.0/lib/puma/configuration.rb", line 224, in call
  File "/app/vendor/bundle/ruby/2.3.0/gems/puma-3.4.0/lib/puma/server.rb", line 569, in handle_request
  File "/app/vendor/bundle/ruby/2.3.0/gems/puma-3.4.0/lib/puma/server.rb", line 406, in process_client
  File "/app/vendor/bundle/ruby/2.3.0/gems/puma-3.4.0/lib/puma/server.rb", line 271, in block in run
  File "/app/vendor/bundle/ruby/2.3.0/gems/puma-3.4.0/lib/puma/thread_pool.rb", line 114, in block in spawn_thread
```

### PR DESCRIPTION
**Pull request by bjmllr**
Resolves #88

The preferred blue-and-green-on-white design is used for the public-facing form, while a black-on-white variant is used in the admin dashboard to provide a visual cue as suggested in #88 .

I used rails_real_favicon to generate these icons from the EPS files provided by the org, which I converted to SVG to serve as a "master" icon.

### CODE REVIEW

**Comment by leesharma** [comment]
Looks good! Two suggestions/questions though:

- It looks like `rails_real_favicon` adds ~9 library dependencies to the project. It looks like it just makes configuration a bit easier, but I don't know too much about the details of how favicons/the gem works. Is it worth it?

- I think it'll be a bit tough to tell at a glance which icon is which on a phone–would it be easy to invert the b/w logo or something to make them easier to distinguish at a glance?

**Comment by leesharma** [comment]
I saved the "check-in" and "admin dashboard" pages to my iPhone (from the right branch this time–sorry!). They look sharp! Nice work @bjmllr.

icon on iPhone

The admin page is still showing up as the color icon though, so we should figure that out.

**Comment by bjmllr** [comment]
Rebased and fixed the home screen issue ... at least on android. I think I may have fixed it for iOS as well but I can't remember I left an iProduct to test with. Haven't yet removed the extra gem nor inverted the b&w icon.

**Comment by leesharma** [comment]
Nice! It looks good on my iPhone too.

img_2908

**Comment by leesharma** [comment]
Oh! I thought of something else. The administrate views use the black icon, but the sign in and report views still use the full-color one (because they don't use the admin layout). Do you all think that's an issue/worth addressing now? It is inconsistent, but those icons aren't likely to be saved on a phone screen.

**Comment by bjmllr** [comment]
Inverted the admin icon and removed the gemfile entry.

I think it would be nice to have all the admin views using `views/layouts/admin/application.html.erb` instead of `views/layouts/application.html.erb`. That would solve the icon issue.

**Comment by leesharma** [comment]
@bjmllr That makes sense–it'll provide a consistent UI too, which is nice.

**Comment by leesharma** [comment]
I added some code that just puts the right icons on the non-administrate admin screens. I'm not entirely comfortable with this solution because of the methods on `ApplicationController`, but doing that allows us to keep all the layout-related code in one place.

I initially tried to get these to work with the `administrate/application` layout we already have, but there were a lot of gotchas; I worry that even if we get it working now, the hacks required to get it working will be confusing down the line.

Thoughts/ideas of a better way to do this?

**Comment by jdsayle** [comment]
I'm wondering if the fact that administrate is an engine is causing the
icon issues? Just a guess on my end . . . Lee, will you be at Arlington
Ruby on Wednesday? If so, I'd like to try and tackle this issue together in
person there.

-JD

**Comment by leesharma** [comment]
I could be!

**Comment by leesharma** [comment]
The other thing to consider is that using Administrate is supposed to save time; at the moment, it seems to be costing time/not letting us do what we want.

It might be worth coming up with some basic fix for this and then rolling our own admin panel.

**Comment by jdsayle** [comment]
Agreed! I'll do some research on my end, but it's looking like administrate
may not be the best option long term and I think you made a great point
earlier about things getting confusing down the line when the app gets into
the maintenance part of it's life cycle.

**Comment by bjmllr** [comment]
What was the issue with devise? We can apply a mix-in to devise's controllers in an initializer.

**Comment by leesharma** [comment]
Oh, neat–I didn't know you could do that!  A devise initializer + adding `layout` (or a module) to the in-app controllers is a much neater solution.

Even with that though, Administrate is limiting what we're able to do (in terms adding "composite" views, etc.), and a lot of the customizations feel hacky. I think it may still be worth moving away from it, even if it's not a priority at the moment.

**Comment by leesharma** [comment]
I changed the code to use the initializer instead of `ApplicationController`, but it adds complexity in a different area: the admin controller name is listed in several places, and adding admin controllers means we need to list it again.

It's probably not worth wrapping in an `ApplicationController` method, module, or new parent class yet (since we only have two non-engine admin controllers), but we may need to in the future.

**Comment by bjmllr** [comment]
Acknowledging that we might rethink our approach to the admin areas later, is this ready for merge?

**Comment by leesharma** [comment]
@bjmllr Are you happy with the icons, or should we do something different for the admin browser logo?

**Comment by bjmllr** [comment]
I think all the icons are good enough. We can always change them later based on feedback.

**Comment by leesharma** [comment]
All right then–looks good to me!

**Pull request merged**
