### PR TITLE
Scope js to check in form Resolves #109

### LINKED ISSUE #109: js error prevents running specs with js enabled
I was trying to write a spec with `js: true`, and got this error:

```
Capybara::Poltergeist::JavascriptError:
       One or more errors were raised in the Javascript code on the page. If you don't care about these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration (see documentation for details).

       TypeError: null is not an object (evaluating 'wrapper.querySelector')
       TypeError: null is not an object (evaluating 'wrapper.querySelector')
```

I think this error occurs on the admin sign in page, and is because `signature.js` runs on all pages, but the admin sign in page doesn't have the signature field. I don't see this error on the admin dashboard, but I think that might have to do with the administrate gem.

### PR DESCRIPTION
**Pull request by AliSchlereth**
@leesharma @crawfoal 
I added an ID of "check-in-form" to the checkins/_form then scoped the functionality within signature.js to run if the ID is present on the page.

I did not add any tests since it was a JS error in the console and it sounds like @crawfoal might already have a test which checks for this?

### CODE REVIEW

**Comment by bjmllr** [comment]
Can we test this by loading the admin login page (`/sign_in`) in a feature spec with `js: true`? Poltergeist should stop the spec on a console error, controlled by `:js_errors` in the [poltergeist config](https://github.com/teampoltergeist/poltergeist#customization).

**Comment by AliSchlereth** [comment]
@bjmllr I'll give it a try!

**Comment by AliSchlereth** [comment]
@bjmllr I added a test that passes locally. When I pushed it up Travis failed so I added the "skip 'PhantomJS 2+ required' unless ENV['RAILS_SPEC_JS']" line that I saw on the other js: true tests in the spec, but it looks like Travis is still failing. I can't see the build logs so I'm not sure where it is going wrong.

**Comment by bjmllr** [comment]
Seems Travis is still suffering from the AWS outage. I'll restart the build when it clears up.

**Comment by bjmllr** [comment]
Looks like the style checker was the only thing failing the build. Running `bundle exec rubocop -a` should make the needed changes to satisfy it.

**Comment by AliSchlereth** [comment]
Thanks @bjmllr, updates made.

**Comment by bjmllr** [comment]
This looks good. Thank you!

**Pull request merged**
