### PR TITLE
Fix work site deletion

### LINKED ISSUE #83: destroying a WorkSite in the dashboard fails if any Shift is still associated
View details in Rollbar: [https://rollbar.com/habitat-nola-signin/habitat-nola-signin/items/5/](https://rollbar.com/habitat-nola-signin/habitat-nola-signin/items/5/)

```

PG::ForeignKeyViolation: ERROR:  update or delete on table "work_sites" violates foreign key constraint "fk_rails_6053284129" on table "shifts"
DETAIL:  Key (id)=(1) is still referenced from table "shifts".

  File "/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb", line 602, in exec_prepared
  File "/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb", line 602, in block in exec_cache
  File "/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract_adapter.rb", line 472, in block in log
  File "/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/notifications/instrumenter.rb", line 20, in instrument
  File "/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract_adapter.rb", line 466, in log
  File "/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb", line 601, in exec_cache
  File "/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb", line 585, in execute_and_clear
  File "/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql/database_statements.rb", line 173, in exec_delete
  File "/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb", line 119, in delete
  File "/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/query_cache.rb", line 14, in delete
  File "/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/relation.rb", line 478, in delete_all
  File "/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/persistence.rb", line 487, in destroy_row
  File "/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/counter_cache.rb", line 152, in destroy_row
  File "/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/locking/optimistic.rb", line 115, in destroy_row
  File "/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/persistence.rb", line 172, in destroy
  File "/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/callbacks.rb", line 292, in block in destroy
  File "/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb", line 88, in __run_callbacks__
  File "/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb", line 778, in _run_destroy_callbacks
  File "/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/callbacks.rb", line 292, in destroy
  File "/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/transactions.rb", line 281, in block in destroy
  File "/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/transactions.rb", line 351, in block in with_transaction_returning_status
  File "/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb", line 213, in block in transaction
  File "/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/transaction.rb", line 184, in within_new_transaction
  File "/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb", line 213, in transaction
  File "/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/transactions.rb", line 220, in transaction
  File "/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/transactions.rb", line 348, in with_transaction_returning_status
  File "/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/transactions.rb", line 281, in destroy
  File "/app/vendor/bundle/ruby/2.3.0/gems/administrate-0.1.5/app/controllers/administrate/application_controller.rb", line 66, in destroy
  File "/app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal/implicit_render.rb", line 4, in send_action
  File "/app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/abstract_controller/base.rb", line 198, in process_action
  File "/app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal/rendering.rb", line 10, in process_action
  File "/app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/abstract_controller/callbacks.rb", line 20, in block in process_action
  File "/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb", line 117, in call
  File "/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb", line 555, in block (2 levels) in compile
  File "/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb", line 505, in call
  File "/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb", line 92, in __run_callbacks__
  File "/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb", line 778, in _run_process_action_callbacks
  File "/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb", line 81, in run_callbacks
  File "/app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/abstract_controller/callbacks.rb", line 19, in process_action
  File "/app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal/rescue.rb", line 29, in process_action
  File "/app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal/instrumentation.rb", line 32, in block in process_action
  File "/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/notifications.rb", line 164, in block in instrument
  File "/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/notifications/instrumenter.rb", line 20, in instrument
  File "/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/notifications.rb", line 164, in instrument
  File "/app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal/instrumentation.rb", line 30, in process_action
  File "/app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal/params_wrapper.rb", line 250, in process_action
  File "/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/railties/controller_runtime.rb", line 18, in process_action
  File "/app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/abstract_controller/base.rb", line 137, in process
  File "/app/vendor/bundle/ruby/2.3.0/gems/actionview-4.2.6/lib/action_view/rendering.rb", line 30, in process
  File

### PR DESCRIPTION
**Pull request by leesharma**
Resolves #83 

Tests and implements a fix to #83–deleting a work site now deletes the associated shifts.

**Other changes:** The `:shift` factory now deincrements days instead of choosing a random one (to avoid day/work site collisions), and a factory test was added to ensure factory validity.

### CODE REVIEW

**Comment by leesharma** [comment]
Ready for review! I added on a basic factory test as well since we didn't have one yet.

**Comment by leesharma** [comment]
Just kidding–saw the discussion on #83. I'll add an archive button.

**Comment by leesharma** [comment]
I'm counting this as done for now, since the desired behavior is implemented (you can activate/deactivate from the work site listings, and you can activate/deactivate as well as destroy from the show page.

The main things I'm not entirely happy with/unsure about:

- Ideally, we'd do activation in a separate `ActivationController`, but I had a hard time getting that to work with Administrate without getting really hacky (it kept getting picked up as an Administrate resource, which threw an error due to the lack of an associated model). For now, I tacked on some controller methods to `Admin::WorkSitesController`. If anyone has a better way of handling this, let me know.

- I'm not sure what the usable css classes are for Administrate, Bourbon, or Neat, so all the buttons are normal blue buttons.

Also, the two controller methods `redirect_back` at the moment since that leads to the expected user flow. I copied the `redirect_back` method from the rails 5 source. If we need it in another controller, we can move it up, but I just left it as a private method in `Admin::WorkSitesController` for now.

**Comment by bjmllr** [comment]
Awesome, thank you!

**Pull request merged**
