### PR TITLE
3-weekly report

### PR DESCRIPTION
**Pull request by scooter-dangle**
WIP branch, but opening PR to associate comments with it. Might want to break the issue up into smaller ones to allow smaller PRs.

See #3

Have ended up shoe-horning in work related to the Shift and ShiftEvent models to support duration calculations [previously thought to be] needed in the report.

UPDATE: This branch was pared down to _just_ returning CSV via the `app.admin_signatures_report_index_path`. Email and delayed jobs will be punted to a separate issue.

### CODE REVIEW

**Comment by scooter-dangle** [comment]
@bjmllr, could you look some at what's in the Shift model and maybe point me in the right direction? (Or someone else in the right direction if they're working on this tomorrow morning.)

**Comment by scooter-dangle** [comment]
@bjmllr, okay to merge?

**Comment by bjmllr** [comment]
:+1:

**Comment by scooter-dangle** [comment]
K *now* I think it's okay to merge.

**Pull request merged**
